name = "JamesCore"
uuid = "979fc264-f091-4d46-bc40-ce8d18beab5d"
authors = ["m410y <m410y@proton.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
